### PR TITLE
 Update discrete speech challenge info

### PR DESCRIPTION
**Pull request by ftshijt**

### CODE REVIEW

**Comment by ftshijt** [comment]
Hi @sw005320 , I've reflected your comments in the last PR. Please let me know if it looks good to update~

**Comment by sw005320** [comment]
This looks broken.
Can you double-check it?

image

**Comment by ftshijt** [comment]
> This looks broken. Can you double-check it?
> 
> image

This is the display issue of the Markdown, while the website goes through the html auto-conversion, there is no issue for the final display.

**Comment by sw005320** [comment]
ok

**Review by sw005320 — APPROVED** [review]

**Pull request merged**
