### PR TITLE
update psc usage

### PR DESCRIPTION
**Pull request by jctian98**
Update the PSC usage instructions.
(1) Change the recommended versions: CUDA=11.7, Torch=1.13.1
(2) If only use Espnet2, clone kaldi but don't need to compile it
(3) avoid using `module` as conda can take care of the related things.

### CODE REVIEW

**Comment by sw005320** [comment]
thx!
@juice500ml, can you check this? (as you might still remember how it was outdated when you read the current tone) ;)

**Comment by sw005320** [comment]
- GPU Partitions: Can you recommend that users work on a single GPU unless they become familiar with GPU usage? This will increase the chances of reducing the queue time. Also, multiple GPU usages are often inefficient and consume the credits uselessly.
- RM Partitions: Please *strongly* recommend using the RM-shared partitions. We can let them know that `RM-512` is only allowed for mature users or those with permission from the lab's main members. Almost all CPU usage is not from our intended use but the misuse due to this.

**Comment by jctian98** [comment]
Updates:
* Add `good practice` paragraph under the `GPU Partitions` and `RM Partitions` sections to emphasize the usage of single GPU and RM-shared partitions.
* Add `(recommended)` to the table `Summary of PSC usage and the partitions`.
* Add `-j 8` to the `make` command for efficient build.

**Comment by juice500ml** [comment]
LGTM 👍

**Comment by sw005320** [comment]
thx!

**Pull request merged**
