### PR TITLE
Update members.md

### PR DESCRIPTION
**Pull request by DanBerrebbi**
Added Dan as a member

### CODE REVIEW

**Comment by ftshijt** [comment]
@DanBerrebbi Hi Dan, seems that you forgot to add the image of your profile, could you please add that through a new PR？ Thanks!

**Comment by DanBerrebbi** [comment]
Hi Jiatong, I tried uploading my picture on the UI but I do not have the right to upload. (see attached picture)
I also tried pushing the picture from the terminal which also gave me a permission error.

What should I do ? 
Thank you,
Dan

Capture d’écran 2021-08-14 à 23 17 28

Capture d’écran 2021-08-14 à 20 27 50

**Comment by ftshijt** [comment]
Hi Dan, please first fork the project and make the modification from your own fork. Then start a PR from your fork to the source-branch at this repo would be fine.

**Comment by DanBerrebbi** [comment]
Ok, I fixed it, thank you !

**Pull request merged**
