### PR TITLE
Update members for fall

### PR DESCRIPTION
**Pull request by ftshijt**

### CODE REVIEW

**Comment by ftshijt** [comment]
Hi @sw005320 , could you verify the date of leaving members (I tried to follow the date on your webpage, but I'm not sure if there is any updates)?

**Comment by sw005320** [comment]
Thanks!
Can you add (co-supervising) to Li-Wei?

**Comment by ftshijt** [comment]
Updated

**Comment by sw005320** [comment]
Thanks!

**Pull request merged**
